services:
  # Frontend - React Application
  - type: web
    name: product-listing-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    plan: free
    healthCheckPath: /
    envVars:
      - key: VITE_PRODUCT_SERVICE_URL
        sync: false
      - key: VITE_SEGMENT_SERVICE_URL
        sync: false

  # Product Service - Main API
  - type: web
    name: product-service
    env: docker
    dockerfilePath: ./backend/services/product-service/Dockerfile
    dockerContext: ./backend/services/product-service
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: product-listing-db
          property: connectionString
      - key: WC_BASE_URL
        sync: false
      - key: WC_CONSUMER_KEY
        sync: false
      - key: WC_CONSUMER_SECRET
        sync: false

  # Segment Service - Segment Evaluation API
  - type: web
    name: segment-service
    env: docker
    dockerfilePath: ./backend/services/segment-service/Dockerfile
    dockerContext: ./backend/services/segment-service
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 3002
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: product-listing-db
          property: connectionString
      - key: PRODUCT_SERVICE_URL
        fromService:
          name: product-service
          type: web
          property: host

  # Cron Service - Background Job for Product Sync
  # NOTE: Background workers require paid plan ($7/mo minimum)
  # Commenting out for free tier deployment
  # You can manually sync products via: POST /api/products/sync
  # 
  # - type: worker
  #   name: cron-service
  #   env: docker
  #   dockerfilePath: ./backend/cron-service/Dockerfile
  #   dockerContext: ./backend/cron-service
  #   plan: starter  # Requires paid plan
  #   envVars:
  #     - key: NODE_ENV
  #       value: production
  #     - key: PRODUCT_SERVICE_URL
  #       fromService:
  #         name: product-service
  #         type: web
  #         property: host
  #     - key: SYNC_INTERVAL
  #       value: 3600000 # 1 hour in milliseconds

databases:
  # PostgreSQL Database (shared by product-service and segment-service)
  - name: product-listing-db
    databaseName: productlisting
    plan: free
    user: productlisting
