name: Product Sync Cron

on:
  schedule:
    # Runs every hour at minute 0
    - cron: '0 * * * *'
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  sync-products:
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger Product Sync
        run: |
          curl -X POST https://product-service-ribm.onrender.com/api/products/sync \
            -H "Content-Type: application/json" \
            -w "\nHTTP Status: %{http_code}\n"
      
      - name: Log Result
        run: echo "Product sync triggered at $(date)"

